import '~/styles/globals.css';

import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';
import { twMerge } from 'tailwind-merge';
import { DungGeunMo } from './_fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="ko">
      <body className={twMerge('center size-full antialiased', DungGeunMo.className)}>
        <div className="h-[600px] w-[800px] bg-black">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
